language: cpp

os: linux
dist: trusty

matrix:
  include:
    - name: "GCC 6"
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - name: "GCC 7"
      os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - name: "Clang"
      os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - name: "MSVC"
      os: windows
      env:
        - MATRIX_EVAL="CC=CL.exe && CXX=CL.exe"

before_install:
    - eval "${MATRIX_EVAL}"

script: 
  - cd build
  - cmake -DCI=1 ..
  - cmake --build test/unittest --target unittest 
  - ctest -C Debug -R unittest --verbose
