name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset prod
        timeout-minutes: 5

      - name: Build
        run: cmake --build --preset prod --parallel
        timeout-minutes: 15

      - name: Test
        run: ctest --preset prod
        timeout-minutes: 10

  sanitizers:
    name: Build and Test (Sanitizers)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset asan
        timeout-minutes: 5

      - name: Build
        run: cmake --build --preset asan --parallel
        timeout-minutes: 15

      - name: Test
        run: ctest --preset asan
        timeout-minutes: 10
